# User Config
# ===========
# fill/change these fields to match your own.

# Identity
# --------

title: Kunanon Burathep      
description: 

logo:  "/assets/img/phanku-logo.png"   #TODO 256x256
cover: "/assets/img/phanku-cover.png"   #TODO 1200x630

baseurl: #TODO leave blank if it is the top path, else use /path/to/sub/dir
url:     #TODO the url without path, don't forget https://

owner:  phanku  
rights: All Right Reserved


# Social & Sharing
# ----------------

google:
  analytics: 
  verification:
  measurement: G-GV0S05TSDS

facebook:
  username:
  app_id:

twitter:
  username:
  large_img: sometimes

disqus:
  username:


# Content Format
# --------------

timezone: London/UK
paginate: 10
mathjax:  true



# ----------------------------------------------------------------------------

# Engine Config
# =============
# you shouldn't change this unless you really know what you're doing.

permalink: date
paginate_path: "/posts/page:num"

collections:
  projects:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md

plugins:
  - jekyll-sitemap
  - jekyll-paginate

empty_array: []
